/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;

import beans.Bebida;
import beans.Comida;
import beans.Sobremesas;
import dao.RestauranteDAO;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.ImageIcon;


/**
 *
 * @author laboratorio
 */
public class Cardapio extends javax.swing.JFrame {
    private RestauranteDAO restauranteDAO;
    /**
     * Creates new form Cardapio
     */
    public Cardapio() {
        initComponents(); // CHAME ISSO PRIMEIRO!
        restauranteDAO = new RestauranteDAO(); // depois crie o DAO
        setSize(715, 528);
        setLocationRelativeTo(null);
        tblCardapio.setRowHeight(50); // agora ele existe
        carregarComidas();

    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCardapio = new javax.swing.JTable();
        btnPedir = new javax.swing.JButton();
        btnComidas = new javax.swing.JButton();
        btnBebidas = new javax.swing.JButton();
        btnSobremesa = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        tblCardapio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "PRODUTO", "PREÇO"
            }
        ));
        jScrollPane1.setViewportView(tblCardapio);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 50, 720, 391);

        btnPedir.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnPedir.setText("Pedir");
        btnPedir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnPedir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPedirActionPerformed(evt);
            }
        });
        getContentPane().add(btnPedir);
        btnPedir.setBounds(320, 450, 42, 23);

        btnComidas.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnComidas.setText("Comidas");
        btnComidas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnComidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComidasActionPerformed(evt);
            }
        });
        getContentPane().add(btnComidas);
        btnComidas.setBounds(30, 10, 66, 23);

        btnBebidas.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnBebidas.setText("Bebidas");
        btnBebidas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBebidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBebidasActionPerformed(evt);
            }
        });
        getContentPane().add(btnBebidas);
        btnBebidas.setBounds(310, 10, 62, 23);

        btnSobremesa.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnSobremesa.setText("Sobremesa");
        btnSobremesa.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSobremesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSobremesaActionPerformed(evt);
            }
        });
        getContentPane().add(btnSobremesa);
        btnSobremesa.setBounds(560, 10, 84, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Restaurante.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-20, -130, 820, 620);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnComidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComidasActionPerformed
        // TODO add your handling code here:
        btnComidas.addActionListener(e -> carregarComidas());
    }//GEN-LAST:event_btnComidasActionPerformed

    private void btnBebidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBebidasActionPerformed
        // TODO add your handling code here:
        btnBebidas.addActionListener(e -> carregarBebidas());

    }//GEN-LAST:event_btnBebidasActionPerformed

    private void btnSobremesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSobremesaActionPerformed
        // TODO add your handling code here:
        btnSobremesa.addActionListener(e -> carregarSobremesas());

    }//GEN-LAST:event_btnSobremesaActionPerformed

    private void btnPedirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPedirActionPerformed
        // TODO add your handling code here:
        Pedidos pedidos = new Pedidos();
        
        pedidos.setVisible(true);
    }//GEN-LAST:event_btnPedirActionPerformed
    ImageIcon icone = new ImageIcon(
    new ImageIcon(getClass().getResource("/imagens/hamburguer.png"))
        .getImage().getScaledInstance(40, 40, java.awt.Image.SCALE_SMOOTH)
);
    private void carregarComidas() {
    List<Comida> comidas = restauranteDAO.buscarComidas();
    
    modelo.setRowCount(0); // limpa as linhas
    modelo.setColumnCount(0); // limpa as colunas (para recriar com imagem)

    modelo.addColumn("IMAGEM");
    modelo.addColumn("NOME");
    modelo.addColumn("CATEGORIA");
    modelo.addColumn("PREÇO");

    for (Comida comida : comidas) {
        if (comida.isDisponivel()) {
            ImageIcon icone = new ImageIcon(
    new ImageIcon(getClass().getResource("/imagens/hamburguer.png"))
        .getImage().getScaledInstance(40, 40, java.awt.Image.SCALE_SMOOTH)
);
            modelo.addRow(new Object[] {
                icone,
                comida.getNome(),
                comida.getCategoria(),
                "R$ " + String.format("%.2f", comida.getPreco())
            });
        }
    }

    tblCardapio.setModel(modelo);
}

    private void carregarBebidas() {
    List<Bebida> bebidas = restauranteDAO.buscarBebidas();

    modelo.setRowCount(0);
    modelo.setColumnCount(0);
    modelo.addColumn("Imagem");
    modelo.addColumn("Nome");
    modelo.addColumn("Categoria");
    modelo.addColumn("Preço");

    for (Bebida bebida : bebidas) {
        if (bebida.isDisponivel()) {
            ImageIcon icone = new ImageIcon(
    new ImageIcon(getClass().getResource("/imagens/cola.png"))
        .getImage().getScaledInstance(40, 40, java.awt.Image.SCALE_SMOOTH)
);
            modelo.addRow(new Object[] {
                icone,
                bebida.getNome(),
                bebida.getCategoria(),
                "R$ " + String.format("%.2f", bebida.getPreco())
            });
        }
    }

    tblCardapio.setModel(modelo);
}

    private void carregarSobremesas() {
    List<Sobremesas> sobremesas = restauranteDAO.buscarSobremesas();

    modelo.setRowCount(0);
    modelo.setColumnCount(0);
    modelo.addColumn("Imagem");
    modelo.addColumn("Nome");
    modelo.addColumn("Categoria");
    modelo.addColumn("Preço");

    for (Sobremesas sobremesa : sobremesas) {
        if (sobremesa.isDisponivel()) {
            ImageIcon icone = new ImageIcon(
    new ImageIcon(getClass().getResource("/imagens/sobremesa.png"))
        .getImage().getScaledInstance(40, 40, java.awt.Image.SCALE_SMOOTH)
);

            modelo.addRow(new Object[] {
                icone,
                sobremesa.getNome(),
                sobremesa.getCategoria(),
                "R$ " + String.format("%.2f", sobremesa.getPreco())
            });
        }
    }

    tblCardapio.setModel(modelo);
}
    
    DefaultTableModel modelo = new DefaultTableModel() {
    @Override
    public Class<?> getColumnClass(int column) {
        // Define a coluna 0 como imagem
        if (column == 0) return ImageIcon.class;
        return String.class;
    }

    @Override
    public boolean isCellEditable(int row, int column) {
        return false;
    }
};

    
    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cardapio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cardapio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cardapio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cardapio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            new Cardapio().setVisible(true);
        }
    });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBebidas;
    private javax.swing.JButton btnComidas;
    private javax.swing.JButton btnPedir;
    private javax.swing.JButton btnSobremesa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblCardapio;
    // End of variables declaration//GEN-END:variables
}
