/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cozinha;
import DAO.CozinhaDAO;
import javax.swing.JOptionPane;

/**
 *
 * @author iagov
 */
public class CadastroProdutos extends javax.swing.JFrame {
    private CozinhaDAO cozinhaDAO;
    
    /**
     * Creates new form CadastroProdutos
     */
    
    public CadastroProdutos() {
        initComponents();
        cozinhaDAO = new CozinhaDAO();
        setSize(450, 400);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgCategorias = new javax.swing.ButtonGroup();
        rdbComidas = new javax.swing.JRadioButton();
        rdbBebidas = new javax.swing.JRadioButton();
        rdbSobremesa = new javax.swing.JRadioButton();
        txtNome = new javax.swing.JTextField();
        lblNome = new javax.swing.JLabel();
        lblPreco = new javax.swing.JLabel();
        txtPreco = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtQuantidade = new javax.swing.JTextField();
        btnCadastrar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        btgCategorias.add(rdbComidas);
        rdbComidas.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        rdbComidas.setForeground(new java.awt.Color(0, 0, 0));
        rdbComidas.setText("Comidas");
        getContentPane().add(rdbComidas);
        rdbComidas.setBounds(42, 250, 100, 24);

        btgCategorias.add(rdbBebidas);
        rdbBebidas.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        rdbBebidas.setForeground(new java.awt.Color(0, 0, 0));
        rdbBebidas.setText("Bebidas");
        getContentPane().add(rdbBebidas);
        rdbBebidas.setBounds(160, 250, 100, 24);

        btgCategorias.add(rdbSobremesa);
        rdbSobremesa.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        rdbSobremesa.setForeground(new java.awt.Color(0, 0, 0));
        rdbSobremesa.setText("Sobremesa");
        getContentPane().add(rdbSobremesa);
        rdbSobremesa.setBounds(250, 250, 130, 24);

        txtNome.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txtNome);
        txtNome.setBounds(160, 90, 130, 20);

        lblNome.setBackground(new java.awt.Color(255, 255, 255));
        lblNome.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        lblNome.setForeground(new java.awt.Color(0, 0, 0));
        lblNome.setText("Nome:");
        getContentPane().add(lblNome);
        lblNome.setBounds(100, 90, 60, 19);

        lblPreco.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        lblPreco.setForeground(new java.awt.Color(0, 0, 0));
        lblPreco.setText("Preço:");
        getContentPane().add(lblPreco);
        lblPreco.setBounds(100, 130, 46, 19);

        txtPreco.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txtPreco);
        txtPreco.setBounds(160, 130, 130, 20);

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Quantidade:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(55, 170, 90, 19);

        txtQuantidade.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txtQuantidade);
        txtQuantidade.setBounds(160, 170, 130, 20);

        btnCadastrar.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnCadastrar.setText("Cadastro");
        btnCadastrar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCadastrar);
        btnCadastrar.setBounds(150, 310, 110, 23);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Fundo.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(-100, 0, 800, 640);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        // TODO add your handling code here:
        
      if (txtNome.getText().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Por favor, informe o nome do produto", 
                "Campo Vazio", JOptionPane.WARNING_MESSAGE);
        return;
    }
    
    if (txtPreco.getText().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Por favor, informe o preço do produto", 
                "Campo Vazio", JOptionPane.WARNING_MESSAGE);
        return;
    }
    
    if (txtQuantidade.getText().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Por favor, informe a quantidade", 
                "Campo Vazio", JOptionPane.WARNING_MESSAGE);
        return;
    }
    
    if (!rdbComidas.isSelected() && !rdbBebidas.isSelected() && !rdbSobremesa.isSelected()) {
        JOptionPane.showMessageDialog(this, "Por favor, selecione uma categoria", 
                "Categoria não selecionada", JOptionPane.WARNING_MESSAGE);
        return;
    }
    
    try {
        String nome = txtNome.getText();
        double preco = Double.parseDouble(txtPreco.getText());
        int quantidade = Integer.parseInt(txtQuantidade.getText()); // Linha adicionada
        
        if (preco <= 0) {
            JOptionPane.showMessageDialog(this, "O preço deve ser maior que zero", 
                    "Preço Inválido", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if (quantidade < 0) {
            JOptionPane.showMessageDialog(this, "A quantidade não pode ser negativa", 
                    "Quantidade Inválida", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // Verificar se produto já existe
        if (cozinhaDAO.produtoExiste(nome)) {
            JOptionPane.showMessageDialog(this, "Já existe um produto com este nome", 
                    "Produto Existente", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // Determinar a categoria
        String categoria = rdbComidas.isSelected() ? "comida" : 
                         rdbBebidas.isSelected() ? "bebida" : "sobremesa";
        
        // Cadastrar no banco
        boolean sucesso = cozinhaDAO.cadastrarProduto(nome, preco, categoria, quantidade);
        
        if (sucesso) {
            JOptionPane.showMessageDialog(this, "Produto cadastrado com sucesso!", 
                    "Sucesso", JOptionPane.INFORMATION_MESSAGE);
            limparCampos();
        } else {
            JOptionPane.showMessageDialog(this, "Erro ao cadastrar produto", 
                    "Erro", JOptionPane.ERROR_MESSAGE);
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Por favor, informe valores numéricos válidos", 
                "Dados Inválidos", JOptionPane.WARNING_MESSAGE);
    }
    }
    
    private void limparCampos() {
        txtNome.setText("");
        txtPreco.setText("");
        txtQuantidade.setText("");
        btgCategorias.clearSelection();
        txtNome.requestFocus();
    
    }//GEN-LAST:event_btnCadastrarActionPerformed
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroProdutos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btgCategorias;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblPreco;
    private javax.swing.JRadioButton rdbBebidas;
    private javax.swing.JRadioButton rdbComidas;
    private javax.swing.JRadioButton rdbSobremesa;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtPreco;
    private javax.swing.JTextField txtQuantidade;
    // End of variables declaration//GEN-END:variables
}
