/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cozinha;

import DAO.CozinhaDAO;
import beans.Bebida;
import beans.Comida;
import beans.Sobremesas;
import javax.swing.JOptionPane;

/**
 *
 * @author iagov
 */
public class DesabilitaProduto extends javax.swing.JFrame {
    private CozinhaDAO cozinhaDAO;

    /**
     * Creates new form DesabilitaProduto
     */
    public DesabilitaProduto() {
        initComponents();
        cozinhaDAO = new CozinhaDAO();
        setSize(420, 250);
        setLocationRelativeTo(null);
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblID = new javax.swing.JLabel();
        btnDesabilitar = new javax.swing.JButton();
        txtID = new javax.swing.JTextField();
        btnHabilitar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        lblID.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        lblID.setForeground(new java.awt.Color(0, 0, 0));
        lblID.setText("ID:");
        getContentPane().add(lblID);
        lblID.setBounds(100, 60, 30, 19);

        btnDesabilitar.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnDesabilitar.setText("Desabilitar");
        btnDesabilitar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnDesabilitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDesabilitarActionPerformed(evt);
            }
        });
        getContentPane().add(btnDesabilitar);
        btnDesabilitar.setBounds(220, 160, 120, 23);

        txtID.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txtID);
        txtID.setBounds(140, 60, 143, 20);

        btnHabilitar.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnHabilitar.setText("Habilitar");
        btnHabilitar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnHabilitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHabilitarActionPerformed(evt);
            }
        });
        getContentPane().add(btnHabilitar);
        btnHabilitar.setBounds(80, 160, 110, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Fundo.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-120, 0, 570, 410);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDesabilitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesabilitarActionPerformed
        // TODO add your handling code here:
       if (txtID.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Informe o ID do produto", 
                    "Campo obrigatório", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            int id = Integer.parseInt(txtID.getText());
            
            // Verifica se o produto existe
            if (!cozinhaDAO.produtoExistePorId(id)) {
                JOptionPane.showMessageDialog(this, "Produto não encontrado", 
                        "Erro", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            // Verifica se já está desabilitado
            if (!cozinhaDAO.verificarDisponibilidade(id)) {
                JOptionPane.showMessageDialog(this, "Produto já está desabilitado", 
                        "Informação", JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            
            // Confirmação
            int confirm = JOptionPane.showConfirmDialog(this,
                    "Deseja realmente desabilitar este produto?",
                    "Confirmação", JOptionPane.YES_NO_OPTION);
            
            if (confirm == JOptionPane.YES_OPTION) {
                if (cozinhaDAO.desabilitarProduto(id)) {
                    JOptionPane.showMessageDialog(this, "Produto desabilitado com sucesso!");
                } else {
                    JOptionPane.showMessageDialog(this, "Falha ao desabilitar produto");
                }
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "ID deve ser um número", 
                    "Erro de formato", JOptionPane.ERROR_MESSAGE);
        }
    
    }//GEN-LAST:event_btnDesabilitarActionPerformed
   
    private void btnHabilitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHabilitarActionPerformed
        // TODO add your handling code here:
         if (txtID.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Informe o ID do produto", 
                    "Campo obrigatório", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        try {
            int id = Integer.parseInt(txtID.getText());
            int confirm = JOptionPane.showConfirmDialog(this,
                    "Deseja realmente habilitar este produto?",
                    "Confirmação", JOptionPane.YES_NO_OPTION);
            
            if (confirm == JOptionPane.YES_OPTION) {
                if (cozinhaDAO.habilitarProduto(id)) {
                    JOptionPane.showMessageDialog(this, "Produto habilitado com sucesso!");
                } else {
                    JOptionPane.showMessageDialog(this, 
                            "Não foi possível habilitar - verifique se há estoque",
                            "Erro", JOptionPane.ERROR_MESSAGE);
                }
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "ID inválido", 
                    "Erro", JOptionPane.ERROR_MESSAGE);
        }
                        
    }//GEN-LAST:event_btnHabilitarActionPerformed
    
     private void limparCampos() {
        txtID.setText("");
        
        txtID.requestFocus();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DesabilitaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DesabilitaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DesabilitaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DesabilitaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DesabilitaProduto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDesabilitar;
    private javax.swing.JButton btnHabilitar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblID;
    private javax.swing.JTextField txtID;
    // End of variables declaration//GEN-END:variables
}
