/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cozinha;

import DAO.CozinhaDAO;
import beans.Bebida;
import beans.Comida;
import beans.Sobremesas;
import javax.swing.JOptionPane;

/**
 *
 * @author iagov
 */
public class ExclusaoProdutos extends javax.swing.JFrame {
    private CozinhaDAO cozinhaDAO;

    /**
     * Creates new form ExclusaoProdutos
     */
    public ExclusaoProdutos() {
        initComponents();
        cozinhaDAO = new CozinhaDAO();
        desabilitarCampos();
        setSize(450, 350);
        setLocationRelativeTo(null);
    }
     private void desabilitarCampos() {
        txtNome.setEnabled(false);
        txtPreco.setEnabled(false);
        txtQuantidade.setEnabled(false);
    }
    private void habilitarCampos() {
        txtNome.setEnabled(true);
        txtPreco.setEnabled(true);
        txtQuantidade.setEnabled(true);
    }
    
    private void limparCampos() {
        txtID.setText("");
        txtNome.setText("");
        txtPreco.setText("");
        txtQuantidade.setText("");
        txtID.requestFocus();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnExcluir = new javax.swing.JButton();
        txtNome = new javax.swing.JTextField();
        lblNome = new javax.swing.JLabel();
        lblPreco = new javax.swing.JLabel();
        txtPreco = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtQuantidade = new javax.swing.JTextField();
        lblID = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        btnVer = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        btnExcluir.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(btnExcluir);
        btnExcluir.setBounds(210, 250, 80, 30);

        txtNome.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });
        getContentPane().add(txtNome);
        txtNome.setBounds(140, 110, 145, 20);

        lblNome.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        lblNome.setForeground(new java.awt.Color(0, 0, 0));
        lblNome.setText("Nome:");
        getContentPane().add(lblNome);
        lblNome.setBounds(80, 110, 47, 19);

        lblPreco.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        lblPreco.setForeground(new java.awt.Color(0, 0, 0));
        lblPreco.setText("Preço:");
        getContentPane().add(lblPreco);
        lblPreco.setBounds(80, 160, 46, 19);

        txtPreco.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txtPreco);
        txtPreco.setBounds(140, 160, 145, 20);

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Quantidade:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 200, 90, 19);

        txtQuantidade.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txtQuantidade);
        txtQuantidade.setBounds(140, 200, 145, 20);

        lblID.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        lblID.setForeground(new java.awt.Color(0, 0, 0));
        lblID.setText("ID:");
        getContentPane().add(lblID);
        lblID.setBounds(100, 30, 30, 19);

        txtID.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txtID);
        txtID.setBounds(140, 30, 143, 20);

        btnVer.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnVer.setText("Ver");
        btnVer.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerActionPerformed(evt);
            }
        });
        getContentPane().add(btnVer);
        btnVer.setBounds(90, 250, 60, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Fundo.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(-120, 0, 750, 510);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // TODO add your handling code here:
        if (txtID.getText().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Informe o ID do produto", 
                "Campo Vazio", JOptionPane.WARNING_MESSAGE);
        return;
    }

    int confirmacao = JOptionPane.showConfirmDialog(
            this, 
            "Tem certeza que deseja excluir este item?", 
            "Confirmação", 
            JOptionPane.YES_NO_OPTION);

    if (confirmacao == JOptionPane.YES_OPTION) {
        try {
            int id = Integer.parseInt(txtID.getText());
            boolean sucesso = cozinhaDAO.excluirProduto(id);

            if (sucesso) {
                JOptionPane.showMessageDialog(this, 
                        "Produto excluído com sucesso!", 
                        "Sucesso", JOptionPane.INFORMATION_MESSAGE);
                limparCampos();
                
            } else {
                JOptionPane.showMessageDialog(this, 
                        "Erro ao excluir produto", 
                        "Erro", JOptionPane.ERROR_MESSAGE);
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, 
                    "ID inválido", 
                    "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }
      
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void btnVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerActionPerformed
        // TODO add your handling code here:
        if (txtID.getText().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Informe o ID do produto", 
                "Campo Vazio", JOptionPane.WARNING_MESSAGE);
        return;
    }

    try {
        int id = Integer.parseInt(txtID.getText());
        Object produto = cozinhaDAO.buscarProdutoPorId(id); // Busca no banco

        if (produto != null) {
            // Preenche os campos conforme o tipo do produto
            if (produto instanceof Comida) {
                Comida c = (Comida) produto;
                txtNome.setText(c.getNome());
                txtPreco.setText(String.format("R$ %.2f", c.getPreco()));
                txtQuantidade.setText(String.valueOf(c.getQuantidade())); // Quantidade direto do banco

            } else if (produto instanceof Bebida) {
                Bebida b = (Bebida) produto;
                txtNome.setText(b.getNome());
                txtPreco.setText(String.format("R$ %.2f", b.getPreco()));
                txtQuantidade.setText(String.valueOf(b.getQuantidade()));

            } else if (produto instanceof Sobremesa) {
                Sobremesas s = (Sobremesas) produto;
                txtNome.setText(s.getNome());
                txtPreco.setText(String.format("R$ %.2f", s.getPreco()));
                txtQuantidade.setText(String.valueOf(s.getQuantidade()));
            }

            
        } else {
            JOptionPane.showMessageDialog(this, 
                    "Nenhum produto encontrado com ID: " + id, 
                    "Não Encontrado", JOptionPane.INFORMATION_MESSAGE);
            limparCampos();
           
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, 
                "ID deve ser um número válido", 
                "Erro de Formato", JOptionPane.ERROR_MESSAGE);
        limparCampos();
    }
    }//GEN-LAST:event_btnVerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExclusaoProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExclusaoProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExclusaoProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExclusaoProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExclusaoProdutos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnVer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblPreco;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtPreco;
    private javax.swing.JTextField txtQuantidade;
    // End of variables declaration//GEN-END:variables
}
